<?php

namespace App\Http\Controllers\Curriculum;

use App\Http\Requests\TypeCrudRequest;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Backpack\CRUD\app\Http\Requests\CrudRequest as StoreRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EducationCrudController extends CrudController
{



    public function setup()
    {
        $this->crud->setModel('App\Models\Education');
        $this->crud->setEntityNameStrings('estudio','estudios');
        $this->crud->setRoute('educations');

        $this->crud->addColumns([
            [
                'name'=>'id',
                'label'=>'ID',
            ],
            [
                'name'=>'name',
                'label'=>'Nombre',

            ],
            [
                'name'=>'order',
                'label'=>'orden',
            ]
        ]);

        $this->crud->addFields([
            [
                'name'=>'name',
                'label'=>'Nombre',

            ],
            [
                'name'=>'order',
                'label'=>'orden',
                'type'=>'number',
            ]
        ]);

    }

    public function store(TypeCrudRequest $request)
    {
        return parent::storeCrud($request); // TODO: Change the autogenerated stub
    }

    public function update(TypeCrudRequest $request)
    {
        return parent::updateCrud($request); // TODO: Change the autogenerated stub
    }

}
