<?php

namespace App\Http\Controllers;

use App\Http\Requests\CandidateCrudRequest;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Http\Request;

class CandidatesCrudController extends CrudController
{


    public function setup()
    {
        $this->crud->setModel('App\Models\Candidate');
        $this->crud->setRoute('candidates');
        $this->crud->setEntityNameStrings('candidato', 'candidatos');

        $this->crud->addColumns([
            [
                'name' => 'id',
                'label' => 'ID',
            ],
            [
                'name' => 'name',
                'label' => 'Nombre',

            ]
        ]);

        $this->crud->addFields([
            [
                'name' => 'name',
                'label' => 'Nombre',

            ]
        ]);


    }



    public function store(CandidateCrudRequest $request)
    {
        return parent::storeCrud($request); // TODO: Change the autogenerated stub
    }

    public function update(CandidateCrudRequest $request)
    {
        return parent::updateCrud($request); // TODO: Change the autogenerated stub
    }


}
