<?php

namespace App\Http\Controllers;

use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Http\Request;
use App\Http\Requests\CandidaciesCrudRequest;

class CandidaciesCrudController extends CrudController
{


    public function setup()
    {
        $this->crud->setModel('App\Models\ElectionCandidate');
        $this->crud->setRoute('candidacies');
        $this->crud->setEntityNameStrings('candidatura', 'candidaturas');

        $this->crud->addColumns([
            [   'label' => "Fecha",
                'type' => 'date',
                'name' => 'election_date',
                'format'=>'Y-m-d'
            ],
            [  // Select2
                'label' => "Candidato",
                'type' => 'select',
                'name' => 'candidate_id',
                'entity' => 'candidate',
                'attribute' => 'full_name',
                'model' => "App\Models\Candidate"
            ],
            [
                'label'=>'Votos proyectados',
                'name'=>'proyected_votes',
                'type'=>'number'
            ],
            [
                'label'=>'Votos obtenidos',
                'name'=>'gotten_votes',
                'type'=>'number'
            ],
	        [
		        'label'=>'Votos partido',
		        'name'=>'party_votes',
		        'type'=>'number'
	        ],
	        [
		        'label'=>'Puesto partido',
		        'name'=>'party_number',
		        'type'=>'number'
	        ],

        ]);

        $this->crud->addFields([
            [   'label' => "Fecha candidatura",
                'type' => 'date_picker',
                'name' => 'election_date',
                'date_picker_options' => [
	                'todayBtn' => true,
	                'format' => 'yyyy-mm-dd',
	                'language' => 'es'
                ],
            ],
            [  // Select2
                'label' => "Candidato",
                'type' => 'select2',
                'name' => 'candidate_id',
                'entity' => 'candidate',
                'attribute' => 'full_name',
                'model' => "App\Models\Candidate"
            ],
            [
                'label'=>'Votos proyectados',
                'name'=>'proyected_votes',
                'type'=>'number'
            ],
	        [
		        'label'=>'Votos obtenidos',
		        'name'=>'gotten_votes',
		        'type'=>'number'
	        ],
            [
                'label'=>'Total del partido',
                'name'=>'party_votes',
                'type'=>'number'
            ],
	        [
		        'label'=>'Puesto partido',
		        'name'=>'party_number',
		        'type'=>'number'
	        ],

        ]);


    }



    public function store(CandidaciesCrudRequest $request)
    {
        return parent::storeCrud($request); // TODO: Change the autogenerated stub
    }

    public function update(CandidaciesCrudRequest $request)
    {
        return parent::updateCrud($request); // TODO: Change the autogenerated stub
    }

}
