<?php

namespace App\Http\Controllers;

use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Http\Request;
use App\Http\Requests\CandidaciesCrudRequest;

class CandidaciesCrudController extends CrudController
{


    public function setup()
    {
        $this->crud->setModel('App\Models\ElectionCandidate');
        $this->crud->setRoute('candidacies');
        $this->crud->setEntityNameStrings('candidatura', 'candidaturas');

        $this->crud->addColumns([
            [   'label' => "Fecha Comicio",
                'type' => 'select',
                'name' => 'date_election',
                'entity' => 'election',
                'attribute' => 'date',
                'model' => "App\Models\Election",
                'format'=>'Y-m-d'
            ],
            [   'label' => "Comicio",
                'type' => 'select',
                'name' => 'election_id',
                'entity' => 'election',
                'attribute' => 'name',
                'model' => "App\Models\Election"
            ],
            [  // Select2
                'label' => "Candidato",
                'type' => 'select',
                'name' => 'candidate_id',
                'entity' => 'candidate',
                'attribute' => 'name',
                'model' => "App\Models\Candidate"
            ],
            [
                'label'=>'Votos proyectados',
                'name'=>'proyected_votes',
                'type'=>'number'
            ],
            [
                'label'=>'Votos obtenidos',
                'name'=>'gotten_votes',
                'type'=>'number'
            ],
            [
                'label'=>'Elegido?',
                'name'=>'elected',
                'type'=>'toggle_switch',
                'switch_labels'=>[
                    'on'=>'Si',
                    'off'=>'No'
                ]
            ],
            [
                'label'=>'Observaciones',
                'name'=>'observation',
                'type'=>'textarea'
            ]

        ]);

        $this->crud->addFields([
            [   'label' => "Comicio",
                'type' => 'select2',
                'name' => 'election_id',
                'entity' => 'election',
                'attribute' => 'name',
                'model' => "App\Models\Election"
            ],
            [  // Select2
                'label' => "Candidato",
                'type' => 'select2',
                'name' => 'candidate_id',
                'entity' => 'candidate',
                'attribute' => 'name',
                'model' => "App\Models\Candidate"
            ],
            [
                'label'=>'Votos proyectados',
                'name'=>'proyected_votes',
                'type'=>'number'
            ],
            [
                'label'=>'Votos obtenidos',
                'name'=>'gotten_votes',
                'type'=>'number'
            ],
            [
                'label'=>'Elegido?',
                'name'=>'elected',
                'type'=>'toggle_switch',
                'switch_labels'=>[
                    'on'=>'Si',
                    'off'=>'No'
                ]
            ],
            [
                'label'=>'Observaciones',
                'name'=>'observation',
                'type'=>'textarea'
            ]

        ]);


    }



    public function store(CandidaciesCrudRequest $request)
    {
        return parent::storeCrud($request); // TODO: Change the autogenerated stub
    }

    public function update(CandidaciesCrudRequest $request)
    {
        return parent::updateCrud($request); // TODO: Change the autogenerated stub
    }

}
