<?php

namespace App\Http\Controllers;

use App\Http\Requests\ElectionSupportCrudRequest;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Http\Request;

class ElectionSupportCrudController extends CrudController
{
    public function setup()
    {
        $this->crud->setModel('App\Models\ElectionUser');
        $this->crud->setRoute('election-supports');
        $this->crud->setEntityNameStrings('registro por usuario', 'registros por usuarios');

        $this->crud->addColumns([
	        [
		        'name'=>'candidacy_id',
		        'label'=>'Candidatura',
		        'type'=>'select',
		        'entity'=>'candidacy',
		        'attribute'=>'full_name'
	        ],
	        [
                'label' => "Usuario",
                'type' => 'select',
                'name' => 'user_id', // the db column for the foreign key
                'entity' => 'user', // the method that defines the relationship in your Model
                'attribute' => 'fullname', // foreign key attribute that is shown to user
                'model' => "App\Models\PublicUser" // foreign key model
            ],
            [
                'label'=>'Total Zonificados',
                'name'=>'zoned'
            ],
            [
                'label'=>'Total planillados',
                'name'=>'registered'
            ],
            [
                'label'=>'Total controlados',
                'name'=>'controlled'
            ],
            [
                'label'=>'Bonificación',
                'name'=>'bonuses'
            ],
            [
                'label'=>'Kit entregado?',
                'name'=>'kit',
                'type'=>'boolean',
                'options' => [0 => 'No', 1 => 'Si']
            ],
            [
                'label'=>'Valor cuota',
                'name'=>'payment'
            ],
            [
                'label'=>'Número de cuotas',
                'name'=>'number_of_payments'
            ],
            [
                'label'=>'Total entregado',
                'name'=>'payroll'
            ],
	        [
		        'label'=>'Transporte entregado',
		        'name'=>'transport_requeriment'
	        ],


        ]);

        $this->crud->addFields([
            [
		        'name'=>'candidacy_id',
		        'label'=>'Candidatura',
		        'type'=>'select2',
		        'entity'=>'candidacy',
		        'attribute'=>'full_name',
	            'attributes'=>['required'=>'required']
	        ],
	        [
		        'label' => "Usuario",
		        'type' => 'select',
		        'name' => 'user_id', // the db column for the foreign key
		        'entity' => 'user', // the method that defines the relationship in your Model
		        'attribute' => 'fullname', // foreign key attribute that is shown to user
		        'model' => "App\Models\PublicUser" // foreign key model
	        ],
	        [
		        'label'=>'Total Zonificados',
		        'name'=>'zoned',
		        'type'=>'number',
		        'attributes'=>['min'=>0,'required'=>'required']
	        ],
	        [
		        'label'=>'Total planillados',
		        'name'=>'registered',
		        'type'=>'number',
		        'attributes'=>['min'=>0,'required'=>'required']
	        ],
	        [
		        'label'=>'Total controlados',
		        'name'=>'controlled',
		        'type'=>'number',
		        'attributes'=>['min'=>0,'required'=>'required']
	        ],
	        [
		        'label'=>'Bonificación',
		        'name'=>'bonuses',
		        'type'=>'textarea',

	        ],
	        [
		        'label'=>'Kit entregado?',
		        'name'=>'kit',
		        'type'=>'toggle_switch',
		        'switch_labels'=>[
			        'on'=>'Si',
			        'off'=>'No'
		        ]
	        ],
	        [
		        'label'=>'Valor cuota',
		        'name'=>'payment',
		        'type'=>'number',
	        ],
	        [
		        'label'=>'Número de cuotas',
		        'name'=>'number_of_payments',
	            'type'=>'number',
		        'attributes'=>['min'=>0,'required'=>'required']
	        ],
	        [
		        'label'=>'Total entregado',
		        'name'=>'payroll',
		        'type'=>'number',
		        'attributes'=>['min'=>0,'required'=>'required']
	        ],
	        [
		        'label'=>'Transporte entregado',
		        'name'=>'transport_requeriment',
		        'type'=>'textarea',
	        ],

        ]);


    }



    public function store(ElectionSupportCrudRequest $request)
    {
        return parent::storeCrud($request); // TODO: Change the autogenerated stub
    }

    public function update(ElectionSupportCrudRequest $request)
    {
        return parent::updateCrud($request); // TODO: Change the autogenerated stub
    }

}
