<?php

namespace App\Http\Controllers;

use App\Http\Requests\ElectionCrudRequest;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Http\Request;

class ElectionCrudController extends CrudController
{

    public function setup()
    {
        $this->crud->setModel('App\Models\Election');
        $this->crud->setRoute('elections');
        $this->crud->setEntityNameStrings('comicio', 'comicios');

        $this->crud->addColumns([
            [
                'name' => 'id',
                'label' => 'ID',
            ],
            [
                'name' => 'date',
                'label' => 'Fecha',
                'type'=>'date',

            ],
            [
                'label' => "Tipo",
                'type' => "select",
                'name' => 'type_id',
                'entity' => 'type',
                'attribute' => "name",
                'model' => "App\Models\ElectionType",
            ],
            [
                'name'=>'name',
                'label'=>'Nombre'
            ]
        ]);

        $this->crud->addFields([
            [   // date_picker
                'name' => 'date',
                'type' => 'date_picker',
                'label' => 'Fecha',
                // optional:
                'date_picker_options' => [
                    'format' => 'yyyy-mm-dd',
                    'language' => 'es'
                ],
            ],
            [  // Select2
                'label' => "Tipo",
                'type' => 'select2',
                'name' => 'type_id',
                'entity' => 'type',
                'attribute' => 'name',
                'model' => "App\Models\ElectionType"
            ],
            [
                'name'=>'name',
                'label'=>'Nombre'
            ]
        ]);


    }



    public function store(ElectionCrudRequest $request)
    {
        return parent::storeCrud($request); // TODO: Change the autogenerated stub
    }

    public function update(ElectionCrudRequest $request)
    {
        return parent::updateCrud($request); // TODO: Change the autogenerated stub
    }


}
