<?php

namespace App\Http\Controllers;

use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Http\Request;
use App\Http\Requests\TypeCrudRequest;

class ElectionTypeCrudController extends CrudController
{


    public function setup()
    {
        $this->crud->setModel('App\Models\ElectionType');
        $this->crud->setRoute('electiontypes');
        $this->crud->setEntityNameStrings('tipo de eleción', 'tipos de eleciones');

        $this->crud->addColumns([
            [
                'name' => 'id',
                'label' => 'ID',
            ],
            [
                'name' => 'name',
                'label' => 'Nombre',

            ],
            [
                'name' => 'order',
                'label' => 'orden',
            ]
        ]);

        $this->crud->addFields([
            [
                'name' => 'name',
                'label' => 'Nombre',

            ],
            [
                'name' => 'order',
                'label' => 'orden',
                'type' => 'number',
            ]
        ]);


    }



    public function store(TypeCrudRequest $request)
    {
        return parent::storeCrud($request); // TODO: Change the autogenerated stub
    }

    public function update(TypeCrudRequest $request)
    {
        return parent::updateCrud($request); // TODO: Change the autogenerated stub
    }


}
