<?php

namespace App\Http\Controllers;

use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Http\Request;
use App\Http\Requests\Curriculum\CreateCurriculumRequest;

class UserCurriculumCrudController extends CrudController
{


    public function setup()
    {
        $this->crud->setModel('App\Models\PublicUser');
        $this->crud->setRoute('curriculums');
        $this->crud->setEntityNameStrings('curriculum', 'curriculums');
        $this->crud->allowAccess('list');
        $this->crud->denyAccess(['update','delete','create']);


        $this->crud->setColumns([
            [
                'label' => '# Documento',
                'name' => 'username',
            ],
            [
                'label' => 'Nombres',
                'name' => 'first_name'
            ],
            [
                'label' => 'Apellidos',
                'name' => 'last_name'
            ],
            'email',
            [
                'label' => 'Perfíl',
                'name' => 'level',
                'type' => 'select',
                'entity' => 'level', // the method that defines the relationship in your Model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'model' => "App\Models\Level" // foreign key model
            ],
            [
                'label' => 'Profesión',
                'name' => 'profession',
                'type' => 'select',
                'entity' => 'profession',
                'attribute' => 'name',
                'model' => 'App.Models.Profession'
            ],
            [
                'label' => 'Líder',
                'name' => 'leader',
                'type' => 'select',
                'entity' => 'leader',
                'attribute' => 'fullname',
                'model' => PublicUser::class,
            ]
        ]);


        $this->crud->addButtonFromModelFunction('line','curriculum','crudHasCurriculum','beginning');

    }

    public function store(CreateCurriculumRequest $request){

        if($request->user()->curriculum){
            return redirect('/');
        }
        return $this->storeCrud($request);

    }

    public function update(CreateCurriculumRequest $request)
    {

        if ($request->input('user_id')!=Auth::user()->id && !Auth::user()->isAdmin()){
            return redirect('/');
        }


        if (empty ($request->get('attachments'))) {
            $request->merge( ['attachments' => '[]']);
        }

        return $this->updateCrud($request); // TODO: Change the autogenerated stub

    }


}
