<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Admin extends User
{


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub



        static::addGlobalScope('admins', function (Builder $builder) {
            $builder->where('rol_id', '=', 1);
        });

    }

}
