<?php

namespace App\Models;

use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Attendance extends Model
{

    use CrudTrait;
    use SoftDeletes;
    protected $fillable=['attende_id','attende_type','attended','attendable_id','attendable_type'];

    protected $casts=[
        'attended'=>'boolean'
    ];




    public function attendable(){
        return $this->morphTo();
    }

    public function attende(){
        return $this->morphTo();
    }

    public function visit(){
        return $this->belongsTo(Visit::class,'attendable_id');
    }

    public function event(){
        return $this->belongsTo(Event::class,'attendable_id');
    }

    public function save(array $options = [])
    {
        return parent::save($options); // TODO: Change the autogenerated stub
    }


}
