<?php

namespace App\Models;

use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class ContractType extends Model
{
    use CrudTrait;
    protected $table='types';

    protected $attributes=[
        'type'=>'contract',
        'order'=>0
    ];

    protected $fillable=['name','order'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('contracts',function(Builder $query){
            return $query->where('type','contract')->orderBy('order','asc');
        });
    }




}
