<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Pivot;

class CurriculumSkill extends Pivot
{


    protected $attributes=[
        'experience'=>0,
    ];

    static function fromRawAttributes(Model $parent, $attributes, $table, $exists = false)
    {
        if (!isset($attributes['experience'])){
            $attributes['experience']=0;
        }
        return parent::fromRawAttributes($parent, $attributes, $table, $exists); // TODO: Change the autogenerated stub
    }

}
