<?php

namespace App\Models;

use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Curriculum extends Model
{

    use CrudTrait;

    protected $table='curriculums';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function user(){
        return $this->belongsTo('App\Models\PublicUser');
    }

    public function birthDepartment(){
        return $this->hasOne('App\Models\Department','birth_dep_id');
    }

    public function birthCity(){
        return $this->hasOne('App\Models\City','birth_city_id');
    }

    public function nationality(){
        return $this->hasOne('App\Models\Country','nationality_id');
    }

    public function currentDepartment(){
        return $this->hasOne('App\Models\Department','current_dep_id');
    }

    public function currentCity(){
        return $this->hasOne('App\Models\City','current_city_id');
    }

    public function currentCountry(){
        return $this->hasOne('App\Models\Country','current_country_id');
    }

}
