<?php

namespace App\Models;

use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class EventStatus extends Model
{

    use CrudTrait;
    protected $table='types';

    protected $attributes=[
        'type'=>'event_status',
        'order'=>0
    ];

    protected $fillable=['name','order'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('event_statuses',function(Builder $query){
            return $query->where('type','event_status')->orderBy('order','asc');
        });
    }


}
