<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;

class PublicUser extends User
{

    protected $table='users';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('users', function (Builder $builder) {
            $builder->where('rol_id', '=', 2 );
        });
    }

    public function crudHasCurriculum(){
        return !$this->curriculum?'':'<a href="http://localhost/gestor/curriculum/'.$this->curriculum->id.'" class="btn btn-xs btn-default"><i class="fa fa-file-text"></i> Curriculum</a>';
    }



}
