<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;

class PublicUser extends User
{

    protected $table='users';

    protected $fillable = [
        'first_name','last_name', 'email', 'password','rol_id','username','level_id','sex','date_of_birth',
        'nationality_id','current_address','current_dep_id','current_city_id','current_country_id','phone',
        'mobile','profession_id',
    ];

    protected $appends=[
        'fullname'
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('users', function (Builder $builder) {
            $builder->where('rol_id', '=', 2 );
        });
    }

    public function crudHasCurriculum(){
        if (!$this->curriculum){
            return '<a href="'.url('curriculum/create?user='.$this->id).'" class="btn btn-xs btn-default"><i class="fa fa-file-text"></i> Crear Curriculum</a>';
        }else{
            return '<a href="'.url('curriculum/'.$this->curriculum->id).'/edit" class="btn btn-xs btn-default"><i class="fa fa-file-text"></i>Editar Curriculum</a> <br/>'.
            '<a href="'.url('curriculum/'.$this->curriculum->id).'" class="btn btn-xs btn-info"><i class="fa fa-file-text"></i> Ver Curriculum</a><br/>';
        }
    }

    public function level(){
        return $this->belongsTo(Level::class);
    }

    public function attendance(){
        return $this->morphTo(Attendance::class,'attende');
    }

    public function getDocumentAttribute(){
        return $this->username;
    }





}
