<?php

namespace App\Models;

use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class VisitStatus extends Model
{


    use CrudTrait;
    protected $table='types';

    protected $attributes=[
        'type'=>'visit-status',
        'order'=>0
    ];

    protected $fillable=['name','order'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('visit_status',function(Builder $query){
            return $query->where('type','visit-status')->orderBy('order','asc');
        });
    }


}
